# Gradient Decent For (I,J,K,X,Y,Z)

In [236]:
import numpy as np
LR=(10^(-8))
Eps=(10^(-3))


In [237]:

OldValue=np.random.randn(6)

In [283]:
OldValue

array([-0.97520481, -0.15149386,  1.01531369,  0.09210379, -0.16952106,
       -0.77289243])

In [284]:
# df/Dx @ Xold

In [264]:
VariableMatrix=np.array([[1,OldValue[0],(OldValue[0])**2],[1,OldValue[1],(OldValue[1])**2],[1,OldValue[2],(OldValue[2])**2],[1,OldValue[3],(OldValue[3])**2],[1,OldValue[4],(OldValue[4])**2],[1,OldValue[5],(OldValue[5])**2]])

In [296]:
VariableMatrix

array([[ 1.        , -0.97520481,  0.95102443],
       [ 1.        , -0.15149386,  0.02295039],
       [ 1.        ,  1.01531369,  1.03086189],
       [ 1.        ,  0.09210379,  0.00848311],
       [ 1.        , -0.16952106,  0.02873739],
       [ 1.        , -0.77289243,  0.59736271]])

In [299]:
v2=np.sum(VariableMatrix,axis=1)

In [300]:
v2

array([ 0.97581961,  0.87145653,  3.04617558,  1.1005869 ,  0.85921633,
        0.82447028])

In [285]:
DellCoff=np.array([[4,4,9],[2,4,9],[4,10,18],[7,16,27],[19,50,96],[108,220,279]])#sabke coff

In [267]:
DellCoff

array([[  4,   4,   9],
       [  2,   4,   9],
       [  4,  10,  18],
       [  7,  16,  27],
       [ 19,  50,  96],
       [108, 220, 279]])

In [268]:
InitialOperation=np.multiply((VariableMatrix),(DellCoff))

In [269]:
InitialOperation

array([[   4.        ,   -3.90081925,    8.55921985],
       [   2.        ,   -0.60597542,    0.20655349],
       [   4.        ,   10.15313689,   18.55551396],
       [   7.        ,    1.47366062,    0.22904391],
       [  19.        ,   -8.47605321,    2.75878956],
       [ 108.        , -170.03633482,  166.66419605]])

In [290]:
FinalDerivative=np.sum(InitialOperation,axis=1)


In [291]:
FinalDerivative

array([   8.6584006 ,    1.60057807,   32.70865085,    8.70270453,
         13.28273635,  104.62786124])

In [246]:
error=np.zeros(6)

In [247]:
error

array([ 0.,  0.,  0.,  0.,  0.,  0.])

In [312]:
while(error!= Eps):
    global error
    NewValues=(InitialOperation.transpose())-LR.FinalDerivative
    InitialOperation=NewValues
    error=np.subtract (OldValue,NewValues)
    OldValue=NewValues
# Funtion ki Initial Values-Func. ki Final values<Epsilon(eps) (abb kro break !!!!!!!11)%
    

<ipython-input-312-fa780c31a168>:2: SyntaxWarning: name 'error' is used prior to global declaration
  global error


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [340]:
NewValues=np.subtract(v2,(LR*(FinalDerivative)))
InitialOperation=NewValues
error=np.subtract (OldValue,NewValues)

print(OldValue)
print("new")
print(NewValues)
print("error")
print(error)

[-0.97520481 -0.15149386  1.01531369  0.09210379 -0.16952106 -0.77289243]
new
[  122.19342799    23.27954954   460.96728746   122.93845033   186.81752517
  1465.6145276 ]
error
[ -123.1686328    -23.4310434   -459.95197378  -122.84634654  -186.98704623
 -1466.38742003]


In [314]:
InitialOperation

array([  122.19342799,    23.27954954,   460.96728746,   122.93845033,
         186.81752517,  1465.6145276 ])